#######################################################################################
# Book settings
title: Schraubenerkennung mit CNN's  # The title of the book
author: Martin Weilepp  # The author of the book to be placed in the footer
copyright: ''  # Copyright year to be placed in the footer
logo: ./figures/Profilbild.png  # A path to the book logo

#######################################################################################
# HTML-specific settings
html:
  favicon: ./figures/favicon-32x32.png  # A path to a favicon image
  navbar_footer_text: Visit my <a href="https://github.com/Martin86We/my_jupyter-book">GitHub
    Repository</a> <div> This book is powered by <a href="https://jupyterbook.org">Jupyter
    Book</a> </div>  # Will be displayed underneath the left navigation bar.
  home_page_in_navbar: false  # Whether to include your home page in the left Navigation Bar
  use_repository_button: true  # Whether to add a link to your repository button
  use_issues_button: true  # Whether to add an "open an issue" button

#######################################################################################
# Launch button settings
repository:
  url: https://github.com/Martin86We/my_jupyter-book  # The URL to your book's repository
  path_to_book: book/website  # A path to your book's folder, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links
